/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 09.06.2026 19:44:15

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1456;
#else
constexpr int kTensorArenaSize = 432;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,84 } };
const TfArray<1, float> quant0_scale = { 1, { 0.36443337798118591, } };
const TfArray<1, int> quant0_zero = { 1, { -106 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[5] = { 78, -98, 11, 12, 7, };
const TfArray<1, int> tensor_dimension1 = { 1, { 5 } };
const TfArray<1, float> quant1_scale = { 1, { 0.0019226046279072762, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[5*10] = { 
  19, -9, -28, 16, -96, 27, 26, -69, 72, 14, 
  42, 42, -55, -34, -77, 82, -47, 47, 36, 29, 
  -80, -49, 1, -67, -34, 55, 89, -13, 17, 23, 
  12, 127, -65, 72, -15, -80, -18, -10, -16, -61, 
  59, -98, -76, 32, -55, 43, 43, -102, -23, 79, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 5,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0091839171946048737, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { 16, 108, 58, 38, 59, 42, 130, -3, -13, -45, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 0.0013045246014371514, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  24, -14, 5, 11, 36, 13, 72, -64, -12, -24, 14, 3, 27, 60, 30, -39, -9, 23, -1, 47, 
  -27, -81, 29, 52, 27, -23, -5, -54, -23, 19, -1, -24, 23, 3, 52, 56, -31, 50, -47, -19, 
  12, -5, -30, 30, -13, -51, -21, 45, -16, -3, 15, 33, -16, -38, 2, -4, 56, -34, -10, -4, 
  24, -34, 90, 33, -37, 51, -9, -57, 27, 21, 68, 17, -18, -56, 28, -12, -17, -10, 70, 38, 
  -36, -43, -64, -10, -33, 56, 0, -10, -17, 55, 60, 29, -23, 6, 33, -35, -50, 11, -12, 11, 
  5, 59, -83, -9, -18, -59, 22, 44, -127, -36, 41, 36, -26, 25, -16, -61, -25, 43, -31, 17, 
  62, 18, -30, -50, 54, 36, 0, 28, -34, 31, 33, 31, -33, 5, 16, 2, 34, -61, 10, -73, 
  -29, 52, 3, 21, -31, 32, 47, -53, 79, -43, -28, 52, 24, -9, -77, 21, 33, 23, -3, 87, 
  43, 69, 59, 27, 42, -3, -84, 47, -12, -38, 32, 10, 10, -35, -44, 61, -15, 87, 38, 57, 
  12, -36, 3, -2, 60, 41, -3, -38, 59, -29, -24, 35, -39, -45, -9, -26, -10, 28, -1, -17, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0087205404415726662, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { 21, 4, 7, -8, 8, 1, 16, 30, -4, 19, 33, 26, -11, 20, 16, 11, -2, 0, 18, 24, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.0044543575495481491, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*84] = { 
  5, -36, -37, -66, -47, 75, 88, -13, 68, 60, 43, 83, -3, -31, 0, 19, 11, -9, -31, -1, 42, -10, 14, 25, -8, 34, 14, -11, -4, 16, 38, 52, 56, -61, -46, -6, 16, -26, -63, -53, -15, 17, -18, 4, -13, -27, -22, 31, 38, -13, -22, 52, 85, 66, -13, 9, 25, -16, -14, -58, -55, 41, 76, -21, -47, 52, 93, 72, 68, 1, 10, -13, -11, -48, -29, 22, 52, 18, 12, 39, 18, 23, -9, 10, 
  -18, 41, 59, -14, -29, 14, 7, 34, -51, 31, 21, 21, -37, 2, 14, -11, 16, 16, 20, -20, -11, -19, 8, -7, 15, 6, 8, 10, -3, 62, 73, 66, 82, -48, -54, 42, -93, -65, -59, -72, -42, 34, 21, 16, 15, 3, 27, -23, 0, -12, -4, -10, -8, -15, 5, -25, -18, 55, 58, 2, 15, 2, -23, -12, 38, -14, 24, -33, 15, 5, 20, -7, 15, 4, 16, 11, -13, -6, 8, 12, -6, -25, -18, -7, 
  18, -14, -32, 48, 75, -63, -57, 21, 76, -67, -102, -62, 17, 21, -2, 15, 2, 25, 19, 11, 1, -2, 28, -45, -42, -35, 14, 17, -9, -33, -31, -27, -48, 45, 32, 10, 45, 44, 85, 31, -3, 5, -6, -13, 2, 29, 14, -24, -39, 48, 14, -67, -82, -63, -20, -7, 3, 53, 51, 97, 118, -119, -99, -15, 20, -89, -126, -111, 64, 6, 12, -24, -3, 50, 8, -47, -50, -13, -25, -51, -31, -50, 10, 2, 
  -18, 5, -15, 35, 15, -4, -21, 8, 33, -36, -7, -4, 23, 0, 5, -10, -19, 2, 10, -1, -26, -14, -26, -17, -3, 0, -28, 10, 13, 6, -15, 13, 14, -4, 16, 3, 45, -17, 9, 15, -16, -6, -3, 11, 16, -2, 8, -19, -2, -1, -26, -12, -14, -31, -20, -6, -19, -19, -8, 22, 41, -16, -4, -11, 6, -41, -16, -40, 7, -18, 11, -14, -13, 1, 13, 0, -16, 31, -6, 1, -16, -6, 3, -17, 
  14, 8, 8, -89, -77, 47, 89, 18, -11, 84, 63, 76, -44, -7, -17, 9, 15, -7, -14, -6, 10, 25, -33, 23, 21, 27, 6, 18, -16, 58, 84, 38, 62, -61, -43, -14, 19, -62, -60, -33, 1, 31, -32, 2, 12, -52, 5, 22, 42, 21, -5, 84, 65, 65, 0, 13, 14, -8, -6, -55, -73, 40, 85, 17, -19, 74, 83, 83, -19, 3, -18, 5, 10, -31, -12, 28, 30, -29, 2, 17, 22, 6, 7, -13, 
  -3, 11, -2, 70, 57, -73, -61, -12, 36, -62, -79, -73, -36, 34, 5, 3, -15, -1, -3, 15, -10, -2, 10, -2, 27, 2, -9, -1, -11, -59, -83, -57, -45, 51, 60, -23, 65, 47, 76, 75, 56, -29, -9, -7, 2, -31, -29, 0, -1, 7, 10, -4, 18, -9, 37, 8, 7, -7, 4, 37, 32, -42, -19, -8, 10, -30, -66, -15, -16, 15, 18, -5, 17, -18, -29, -20, 3, -33, -22, 19, 28, 26, 2, 14, 
  17, 56, 55, 17, 39, -69, -31, -31, 23, -33, -32, -36, 1, 41, 10, 1, 1, -60, -30, 44, 36, 6, -46, 65, 47, 50, 16, -11, 24, 16, 23, -25, -8, 0, 1, 34, -34, 16, -10, 28, -48, -27, -7, 12, -5, -97, -16, 26, 75, -42, -34, 105, 65, 101, -1, -1, 9, 35, 32, -75, -71, 62, 79, 29, 2, 69, 89, 76, -22, -16, 8, 23, 1, -53, -40, 62, 70, 35, 25, 36, 57, 57, -15, 5, 
  21, -81, -55, -61, -62, 78, 83, 52, -58, 94, 70, 96, -25, -36, -4, -10, 4, 4, -15, 10, 11, -36, -7, 2, -1, 21, -5, 7, -7, 53, 62, 84, 91, -102, -78, -20, -57, -69, -82, -81, -8, 47, 28, 33, 21, 38, 6, -27, -34, 3, 8, -27, -44, -19, 3, -2, -6, -24, -25, -82, -71, 61, 65, -35, -18, 64, 69, 50, -21, 17, -5, 17, 9, 21, 10, 8, -22, 17, 13, 6, 3, -23, 9, 5, 
  12, 35, 25, 83, 57, -63, -83, -28, 57, -85, -76, -70, -16, -1, 2, -3, 12, 14, 42, -7, 0, -27, 55, -2, 10, 3, 26, 1, 12, -73, -45, -30, -22, 21, -4, 15, 20, 32, 5, 17, 21, -29, -15, -14, -26, 22, 12, -13, -55, 48, -37, -50, -13, -43, 31, 12, 3, 39, 27, 62, 78, -61, -48, -40, 71, -86, -79, -53, 41, -57, -4, -9, -1, 22, 8, -52, -54, -13, -59, -21, -47, -48, -34, -16, 
  -8, -27, -54, 5, -43, 34, -11, -7, -44, -11, 23, -4, -4, 3, -3, 26, 6, 8, 15, 5, 6, 38, 27, 19, 21, 14, -5, 13, 6, -68, -85, -76, -82, 70, 80, 7, 49, 84, 70, 72, 40, -15, 6, 12, 4, 0, -11, 17, -2, -43, 9, -31, -70, -68, -15, 6, 19, -32, -52, 10, -25, 5, -17, 27, 7, -2, -68, -3, -76, 5, -7, 26, 32, 8, -11, -19, 6, -26, -73, 26, 42, 31, -11, 3, 
  31, -18, -13, -4, 11, -23, 9, -38, 32, -6, -48, -6, 56, 12, 24, 2, 11, -21, -15, 32, 5, 25, -16, 16, 7, -3, -13, 2, 28, -41, -74, -74, -68, 49, 73, 9, -33, 40, 38, 60, -22, -13, 19, 8, 10, 6, -23, 1, 26, -15, 3, -33, -33, -22, 1, 27, 1, -49, -36, -36, -27, 35, 42, 60, -2, 9, -8, 37, 4, 7, 28, 17, 11, -22, -19, 51, 24, 28, 56, 18, -13, -15, 30, 4, 
  6, 46, 58, -37, -44, -4, 45, -13, -42, 23, 69, 45, -5, 19, 0, 18, 4, -25, -7, 12, 12, -9, 1, 23, 30, 30, 16, 7, 29, 51, 44, 8, 10, -20, 1, -15, -27, -4, -5, 2, 19, 23, 19, 10, 0, -46, -14, 29, 18, -15, -9, 61, 54, 55, 32, 11, 20, 9, 15, -67, -37, 63, 48, 0, -16, 64, 97, 48, -38, -1, -7, 10, -2, -41, -2, 30, 41, 7, 51, 28, 29, 42, -17, -9, 
  -13, -25, -4, -2, 16, -21, -16, -23, -15, 5, -8, -22, 11, 18, -11, 10, -2, -2, 21, -11, 4, 8, -18, 10, 12, -8, -2, -10, 12, -10, -13, 7, -16, 15, 8, 19, 17, -16, -19, -15, -7, -1, -20, -14, -24, -2, 23, 6, -9, 23, 13, -22, -24, -2, -13, -20, -18, 2, -8, 13, -1, -18, -21, 21, 7, 1, 9, 4, -1, 12, -5, -13, 5, 18, 10, -25, -13, 15, -21, -21, -1, 4, 15, 9, 
  11, 13, 23, -49, -6, 39, 36, -15, -1, 47, 43, 47, 19, 3, 1, -7, -8, -33, -56, 4, 17, -42, -40, 22, 16, 9, -29, 19, 7, 41, 49, 8, 23, -60, -33, 25, -40, -35, -35, -39, -28, 1, 15, -2, 25, -51, -17, 27, 71, -17, 29, 69, 55, 50, 27, -10, 13, 10, 9, -91, -78, 78, 81, 30, 12, 97, 127, 97, -6, 7, -12, 3, 18, -39, -11, 25, 29, 46, 54, 17, 18, 37, -6, -1, 
  24, -43, -38, -16, -13, 13, 25, -33, 54, 31, 19, 5, -3, 17, -12, 0, -11, -15, 1, 9, 37, 63, 35, 28, -15, 3, -49, -27, 21, -65, -40, -72, -73, 75, 56, -2, -9, 67, 77, 44, -40, -24, -12, 20, 4, -1, -28, -1, -3, -32, -31, 17, 4, 5, -16, -19, 24, -34, -13, -53, -35, 51, 31, 67, 20, 57, 45, 51, -23, 5, 7, -6, 23, -24, -4, 22, 3, -14, -24, 12, 2, 12, 16, 3, 
  4, -17, -49, -9, -30, 19, -18, 48, 11, 1, -11, 2, -12, -30, 16, 19, 5, 36, 42, -5, -45, 39, 33, -22, -32, -30, 3, -9, -2, 26, 42, 30, 22, -16, -36, 2, 52, -50, -23, -15, 36, 14, 15, -17, 12, 28, 13, -27, -65, 76, -8, -54, -37, -36, 1, -6, 19, 53, 29, 94, 82, -97, -74, -47, 26, -70, -102, -89, 16, 24, -11, 14, 15, 57, 35, -28, -51, -24, -14, -26, -54, -45, 7, 15, 
  -1, -23, -22, -19, 0, 9, 8, 1, -7, -1, 4, 10, -3, 9, -9, 7, -16, -15, 9, -1, -10, 7, 13, -3, 13, -1, 7, 14, -15, 26, 19, 14, 37, -35, -25, -1, -18, -36, -34, -18, 12, 16, 2, 14, -2, -17, 15, -20, 2, -6, 3, 0, 0, -12, -4, -20, -5, -3, 13, -23, -25, 27, 3, 12, -12, 19, 15, 3, -5, 17, -16, -4, -10, 10, 14, 8, -5, -15, -19, 6, 9, 20, -29, -11, 
  -1, 59, 68, 77, 76, -65, -81, 11, 8, -69, -73, -48, -35, 0, -12, -10, -17, 18, 34, -28, -13, -15, -48, -1, -30, -36, -22, -1, -3, 54, 61, 31, 35, -34, -44, 32, 9, -53, -11, -59, -19, 26, 21, -11, 1, 11, 27, 4, -38, 28, -4, -38, -9, -16, -38, -15, 14, 50, 64, 68, 80, -95, -66, -4, 34, -67, -88, -77, 35, -2, 17, -12, 10, 41, 27, -23, -40, -36, -4, -40, -42, -42, -18, 5, 
  -9, -47, -34, -15, 32, -6, -22, -5, 42, -17, -51, -18, -4, -12, -7, -8, 3, -14, -15, 14, -14, 6, -7, 16, -9, -17, 21, 0, -10, -3, 19, -5, -17, -9, 14, 13, 2, -16, -7, -9, -20, 3, -1, 12, 3, -6, 26, 2, -21, 14, -10, -22, 9, -17, 1, -17, -5, 11, 16, 50, 26, -66, -32, 15, 21, -43, -24, -49, 43, 10, 24, 15, 22, -11, -30, 15, 18, 17, 5, -6, -10, -5, -1, 6, 
  11, 79, 65, 65, 66, -79, -75, -16, 28, -63, -89, -61, -3, 16, 10, 1, 8, 6, 4, -14, -35, -27, -23, -40, -34, -24, -19, -49, 13, 59, 28, 64, 58, -56, -44, -7, 25, -45, -46, -51, 36, 20, 15, 13, 2, 14, 11, -7, -34, 58, 70, -25, -69, -27, 22, 3, 19, 53, 56, 99, 67, -73, -97, -35, -10, -86, -99, -97, 20, 21, -8, 11, -5, 32, 20, -26, -51, 2, -45, -45, -43, -37, -45, -23, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,84 } };
const TfArray<1, float> quant6_scale = { 1, { 0.012222693301737309, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.14959217607975006, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 0.20934472978115082, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,5 } };
const TfArray<1, float> quant9_scale = { 1, { 0.27585980296134949, } };
const TfArray<1, int> quant9_zero = { 1, { -25 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 84, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 50, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 1680, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 96), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 5, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 5, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1023480_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1023480_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1023480_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1023480_3_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1023480_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
